### ISSUE TITLE
'class QOpcUaConnectionSettings' has no member named 'setSessionName'

### ISSUE THREAD

**Issue by Curr93** [sanny32/OpenUaExplorer#12]
Thank you for sharing your code! Do you compiled your project in Qt 6.9.0 or other?
When I'm compiling your project in Qt 6.11.2, a blocking error occurs: "src\core\opcua\qtopcuaconnectionmanager.cpp:577: error: 'class QOpcUaConnectionSettings' has no member named 'setSessionName'; did you mean 'setSessionTimeout'?"

Apparently, the new 6.11.2 is quite different from Qt 6.9

**Comment by sanny32** [comment]
Thank you for the report. The project is currently builds with Qt 6.9.3. `setSessionName()` is not part of the official Qt API; `OpenUaExplorer` adds it by patching the Qt OPC UA sources that it builds automatically.
The project built successfully using Qt 6.11.2 on my Windows 11 laptop.
Could you please try configuring in a completely new build directory and attach the CMake output around the “Qt OpcUa” messages? Please also provide the value of `Qt6OpcUa_DIR` from `CMakeCache.txt`. This will show whether CMake reused an older unpatched backend.

**Comment by Curr93** [comment]
Hello dear Alexandr! 
In advance I'd like to say that I'm working in MSYS2 Qt Installation in Windows 10.  
I think that cause my issue is in MSYS2 environment and paths.

In the CMake output around Qt OPC UA, the important part is:

-- Applying qtopcua patch 0001...
-- Applying qtopcua patch 0002...
-- Applying qtopcua patch 0003-open62541-plugin-certificate-errors-are-trust-decisions.patch
-- Applying qtopcua patch 0004-open62541-plugin-send-a-session-name.patch
-- Applying qtopcua patch 0005...
-- Applying qtopcua patch 0006...
-- Configuring Qt OpcUa 6.11.2 with bundled open62541 backend

So the relevant CMakeCache.txt value is:
Qt6OpcUa_DIR:PATH=C:/Qt_Projects/OpenUaExplorer/Build.Ideal.Qt6112/_deps/qtopcua-install/lib/cmake/Qt6OpcUa

also explicitly configured:
-DCMAKE_DISABLE_FIND_PACKAGE_Qt6OpcUa=FALSE
The project then configures and generates successfully.

However, when compiling the original Ideal source, qtopcuaconnectionmanager.cpp fails here:
settings.setSessionName(profile.sessionName);
with error: 'class QOpcUaConnectionSettings' has no member named 'setSessionName'

I investigated further and found that there are two QtOpcUa header trees:

MSYS2 system QtOpcUa:
C:/msys64/ucrt64/include/qt6/QtOpcUa    // This one does NOT contain setSessionName().

The patched your "Ideal" qtopcua installation:
C:/Qt_Projects/OpenUaExplorer/Build.Ideal.Qt6112/_deps/qtopcua-install/include/qt6/QtOpcUa
//This one DOES contain setSessionName().

**Comment by sanny32** [comment]
Thank you, this identifies the likely cause: the compiler is selecting the unpatched MSYS2 Qt OPC UA headers instead of the patched headers from `_deps/qtopcua-install`.
Could you please rebuild with verbose output and attach the complete compiler command for `qtopcuaconnectionmanager.cpp`?
`cmake --build Build.Ideal.Qt6112 --verbose`
I need to check the order of the two QtOpcUa include directories. The patched `_deps/qtopcua-install/include/qt6/QtOpcUa` directory must precede the MSYS2 directory.

**Comment by Curr93** [comment]
Please see the attached file
[build_verbose.txt](https://github.com/user-attachments/files/32336996/build_verbose.txt)

**Comment by sanny32** [comment]
Thank you, the verbose command confirms the cause. The MSYS2 Qt include root appears before the patched Qt OPC UA include root, so nested includes such as `<QtOpcUa/qopcuaconnectionsettings.h>` resolve to the unpatched MSYS2 header. This is a build-system include-order bug. I’ll adjust the CMake target dependency order so the bundled patched Qt OPC UA headers take precedence.

**Comment by sanny32** [comment]
@Curr93 can you test new building from sources using `dev` branch?

**Comment by Curr93** [comment]
> [@Curr93](https://github.com/Curr93) can you test new building from sources using `dev` branch?
I’m sorry, but yesterday I deleted the entire MSYS2 and all the Qt components installed in it, so nothing is working. I’m now finishing the installation via the standard Online installer and the Maintenance tool. Let’s close the issue. Thank you once again.
